[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DomainIntegrals = "cc6bae93-f070-4015-88fd-838f9505a86c"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
QuantumOpticalCircuits = "83ed5d67-5d37-4206-9503-909fa450860a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
